// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace WebApplication_10052021.DataAccess.DbModels
{
    public partial class DB_TestContext : DbContext
    {
        public DB_TestContext()
        {
        }

        public DB_TestContext(DbContextOptions<DB_TestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tb_City> tb_Cities { get; set; }
        public virtual DbSet<tb_Register> tb_Registers { get; set; }
        public virtual DbSet<tb_State> tb_States { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tb_City>(entity =>
            {
                entity.ToTable("tb_City");

                entity.Property(e => e.City).HasMaxLength(50);

                entity.Property(e => e.State).HasMaxLength(50);
            });

            modelBuilder.Entity<tb_Register>(entity =>
            {
                entity.ToTable("tb_Register");

                entity.Property(e => e.Address).HasMaxLength(100);

                entity.Property(e => e.DOB).HasColumnType("datetime");

                entity.Property(e => e.Gender).HasMaxLength(50);

                entity.Property(e => e.Mobile).HasMaxLength(10);

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.Salary).HasColumnType("numeric(18, 2)");

                entity.Property(e => e.State).HasMaxLength(50);
            });

            modelBuilder.Entity<tb_State>(entity =>
            {
                entity.ToTable("tb_State");

                entity.Property(e => e.State).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}