// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApplication_10052021.DataAccess.DbModels
{
    public partial class tb_City
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    }
}