// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApplication_10052021.DataAccess.DbModels
{
    public partial class tb_Register
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string State { get; set; }
        public decimal? Salary { get; set; }
        public DateTime? DOB { get; set; }
    }
}